# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=debug64
endif
export config

PROJECTS := pipeRunner

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

pipeRunner: 
	@echo "==== Building pipeRunner ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f pipeRunner.make

clean:
	@${MAKE} --no-print-directory -C . -f pipeRunner.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   debug64"
	@echo "   release64"
	@echo "   debug32"
	@echo "   release32"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   pipeRunner"
